version: 2
# This is an example goreleaser.yaml file with some defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - CGO_ENABLED=1
before:
  hooks:
    - make go.lint
    - make go.test
    - brew install filosottile/musl-cross/musl-cross
builds:
  - id: linux-amd64
    env:
      - CC=x86_64-linux-musl-gcc
      - CXX=x86_64-linux-musl-g++
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - cmd: bash -c "chmod +x {{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
          dir: "{{ dir .Path }}"
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}'
      - '-linkmode external -extldflags "-static"'
    goos:
      - linux
    goarch:
      - amd64
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    no_unique_dist_dir: true
  - id: linux-arm64
    env:
      - CC=aarch64-linux-musl-gcc
      - CXX=aarch64-linux-musl-g++
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - cmd: bash -c "chmod +x {{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
          dir: "{{ dir .Path }}"
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}'
      - '-linkmode external -extldflags "-static"'
    goos:
      - linux
    goarch:
      - arm64
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    no_unique_dist_dir: true
  - id: darwin-amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - cmd: bash -c "chmod +x {{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
          dir: "{{ dir .Path }}"
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}'
    goos:
      - darwin
    goarch:
      - amd64
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    no_unique_dist_dir: true
  - id: darwin-arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - cmd: bash -c "chmod +x {{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
          dir: "{{ dir .Path }}"
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}'
    goos:
      - darwin
    goarch:
      - arm64
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    no_unique_dist_dir: true
# archives:
#   - id: archive
#     formats: ['zip']
#     name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
#     files:
#       - '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}.zip'
# checksum:
#   name_template: 'checksums.txt'
release:
  disable: true
  # extra_files:
  # - glob: ./docs.zip
  # disable: true
changelog:
  disable: true
