version: '3.1'
services:
  anklet:
    build:
      context: ./
      dockerfile: Dockerfile
    # image: veertu/anklet:latest
    container_name: anklet
    volumes:
      - /Users/nathanpierce/.config/anklet:/root/.config/anklet/
    ports: 
      - "8081:8081"
    environment:
      # - LOG_LEVEL=dev
      - ANKLET_CONFIG_FILE_NAME=org-receiver-config.yml
      ##################################################################################
      # ANKLET_GLOBAL_PRIVATE_KEY allows you to use the same private key for all runners
      # instead of defining a different one in the config.yml file for each runner.
      # You can also set it to be the PEM contents, vs pointing to a file.
      # - ANKLET_GLOBAL_PRIVATE_KEY=/Users/nathanpierce/veertuinc-anklet.2024-07-19.private-key.pem
      # - |-
      #   ANKLET_GLOBAL_PRIVATE_KEY=-----BEGIN RSA PRIVATE KEY-----
      #   MIIEpAIBAAKCAQEAyqZDXOEzV5gRocWAhH73chGjn4HBh1UCG2Du4v9JmcjfyYT3
      #   . . .
      #   -----END RSA PRIVATE KEY-----
      ################################################################
      # AGGREGATOR
      # - ANKLET_METRICS_AGGREGATOR=true
      # - ANKLET_METRICS_PORT=8081 
      # - ANKLET_METRICS_URLS=http://host.docker.internal:8080/metrics # comma separation for multiple urls
      # - ANKLET_METRICS_SLEEP_INTERVAL=10
      # - ANKLET_METRICS_DATABASE_ENABLED=true
      # - ANKLET_METRICS_DATABASE_URL=host.docker.internal
      # - ANKLET_METRICS_DATABASE_PORT=6379
      # - ANKLET_METRICS_DATABASE_USER=
      # - ANKLET_METRICS_DATABASE_PASSWORD=
      # - ANKLET_METRICS_DATABASE_DATABASE=0

