name: Build Release Artifacts

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref (branch, tag, or SHA) to checkout and build"
        required: true
        default: "edge"
        type: string

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
      - run: git tag $(cat VERSION)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.1
          cache: false
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
            name: goreleaser-archive
            path: dist/*
            retention-days: 1