name: Check Build

on:
  workflow_dispatch:
  pull_request:
    branches-ignore: []
  push:
    branches:
      - edge
  
jobs:

  goreleaser:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
      # - run: git tag $(cat VERSION)
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.1
          cache: false
      - name: Run GoReleaser build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: build --single-target --snapshot --clean