name: Check PR

on:
  workflow_dispatch:
  pull_request:
    branches-ignore: []
jobs:

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      # - run: git tag $(cat VERSION)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.1
          cache: false
      - name: Run GoReleaser build
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: build --single-target --snapshot --clean