name: 't1-cancelled-failure-no-template-specified'
on:
  workflow_dispatch:

jobs:
  testJob:
    runs-on: [ 
      "anka-template-tag:vanilla+port-forward-22+brew-git",
    ]
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "hello"
