name: 't1-with-tag-2'
on:
  workflow_dispatch:

jobs:
  testJob:
    runs-on: [ 
      "self-hosted", 
      "anka", 
      "anka-template:d792c6f6-198c-470f-9526-9c998efe7ab4", 
      "anka-template-tag:vanilla+port-forward-22",
    ]
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -laht
          sw_vers
          hostname
          echo "123"