# This workflow is used to test a template with too much CPU for the host, causing it to be sent back to the queue
name: 't2-20c20r-1'
on:
  workflow_dispatch:

jobs:
  t2-20c20r-1:
    runs-on: [ 
      "${{ github.run_id }}-${{ strategy.job-index }}",
      "anka-template:84266873-da90-4e0d-903b-ed0233471f9f", 
      "anka-template-tag:20c20r",
    ]
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -laht
          sw_vers
          hostname
          echo "123"
          sysctl -n hw.ncpu
      - run: whoami
